// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";

function ExampleComponent(Props) {
  var name = Props.name;
  return React.createElement(React.Fragment, undefined, React.createElement("p", undefined, "Hello " + name));
}

var make = ExampleComponent;

export {
  make ,
  
}
/* react Not a pure module */
