// Generated by ReScript, PLEASE EDIT WITH CARE


var ExampleData = {
  variable: 1,
  otherVariable: 2
};

var exampleUseWithoutOpen = 3;

var WithOutOpen = {
  exampleUseWithoutOpen: exampleUseWithoutOpen
};

var exampleUseWithOpen = 3;

var WithOpen = {
  exampleUseWithOpen: exampleUseWithOpen
};

export {
  ExampleData ,
  WithOutOpen ,
  WithOpen ,
  
}
/* No side effect */
