// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Curry from "../../../node_modules/bs-platform/lib/es6/curry.js";
import * as React from "react";
import * as Core from "@material-ui/core";
import * as Product$ReactTypescriptReasonTraining from "../../constants/Product.bs.js";
import * as CartUtils$ReactTypescriptReasonTraining from "../../utils/CartUtils.bs.js";
import * as ProductTable$ReactTypescriptReasonTraining from "../ProductTable/ProductTable.bs.js";

function App(Props) {
  var match = React.useState(function () {
        return Product$ReactTypescriptReasonTraining.productDetails;
      });
  var setCart = match[1];
  var cart = match[0];
  var match$1 = React.useState(function () {
        return 0.0;
      });
  var setCalculatedPrice = match$1[1];
  var deleteFromCart = function (id) {
    var updatedCart = CartUtils$ReactTypescriptReasonTraining.findIndexAndUpdateQuantity(cart, id, 0);
    return Curry._1(setCart, (function (param) {
                  return updatedCart;
                }));
  };
  var updateCart = function (id, value) {
    var updatedCart = CartUtils$ReactTypescriptReasonTraining.findIndexAndUpdateQuantity(cart, id, value);
    return Curry._1(setCart, (function (param) {
                  return updatedCart;
                }));
  };
  return React.createElement(React.Fragment, undefined, React.createElement(Core.Typography, {
                  align: "center",
                  children: "Welcome to the React Type Demo App",
                  variant: "h3"
                }), React.createElement(Core.Typography, {
                  align: "center",
                  children: "Here you can buy some items for your team",
                  variant: "body1"
                }), React.createElement(Core.Container, {
                  children: null
                }, React.createElement(ProductTable$ReactTypescriptReasonTraining.make, {
                      deleteFromCart: deleteFromCart,
                      updateCart: updateCart,
                      cart: cart
                    }), React.createElement(Core.Card, {
                      children: null,
                      className: "shopping-cart"
                    }, React.createElement(Core.Button, {
                          onClick: (function (param) {
                              var totalPrice = CartUtils$ReactTypescriptReasonTraining.calculateTotalPrice(cart, 0.0);
                              return Curry._1(setCalculatedPrice, (function (param) {
                                            return totalPrice;
                                          }));
                            }),
                          children: "Calculate Price",
                          color: "primary",
                          variant: "contained"
                        }), React.createElement("h3", undefined, "Your total is"), React.createElement("h3", undefined, match$1[0].toFixed(2)))));
}

var make = App;

export {
  make ,
  
}
/* react Not a pure module */
