// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Belt_Array from "../../node_modules/bs-platform/lib/es6/belt_Array.js";
import * as Belt_Option from "../../node_modules/bs-platform/lib/es6/belt_Option.js";

function calculateProductPrice(product) {
  var quantity = Belt_Option.getWithDefault(product.quantity, 0);
  var price = Belt_Option.getWithDefault(product.price, 0.0);
  return price * quantity;
}

function combinePriceCalculations(balance, product) {
  return balance + calculateProductPrice(product);
}

function calculateTotalPrice(cart, initialCartValue) {
  return Belt_Array.reduce(cart, initialCartValue, combinePriceCalculations);
}

function evaluateProductQuantity(id, updatedQuantity, product) {
  if (product.id === id && product.quantity !== updatedQuantity) {
    return {
            id: product.id,
            name: product.name,
            price: product.price,
            quantity: updatedQuantity,
            description: product.description
          };
  } else {
    return product;
  }
}

function findIndexAndUpdateQuantity(cart, id, quantity) {
  var evaluateProduct = function (param) {
    return evaluateProductQuantity(id, quantity, param);
  };
  return Belt_Array.map(cart, evaluateProduct);
}

export {
  calculateProductPrice ,
  combinePriceCalculations ,
  calculateTotalPrice ,
  evaluateProductQuantity ,
  findIndexAndUpdateQuantity ,
  
}
/* No side effect */
