// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as ReactDOMRe from "../node_modules/reason-react/src/legacy/ReactDOMRe.bs.js";
import AppJsx from "./components/App/App.jsx";

var make = AppJsx;

var App = {
  make: make
};

ReactDOMRe.renderToElementWithId(React.createElement(make, {}), "root");

export {
  App ,
  
}
/* make Not a pure module */
