// Generated by ReScript, PLEASE EDIT WITH CARE


var floatVariable = 12.1 + 12.5;

var stringVariable = "Hello James";

var integerVariable = 24;

export {
  stringVariable ,
  integerVariable ,
  floatVariable ,
  
}
/* No side effect */
